jenkins:
  ports:
    - "8080:8080"
  build: jenkins/
  dockerfile: /home/ubuntu/dockerProject/jenkins/Dockerfile
  volumes:
    - /home/ubuntu/dockerProject/shared/:/var/lib/jenkins
  tty: true
  stdin_open: true

nexus:
  ports: 
    - "8081:8081"
  build: nexus/
  dockerfile: /home/ubuntu/dockerProject/nexus/Dockerfile
  volumes:
    - /home/ubuntu/dockerProject/shared/:/var/lib/nexus

jira:
  ports: 
    - "8082:8082"
  build: jira/
  dockerfile: /home/ubuntu/dockerProject/jira/Dockerfile
  volumes:
    - /home/ubuntu/dockerProject/shared/:/var/lib/jira

zabbix_server:
  ports:
    - "10051:10051"
    - "80:80"
  build: zabbix_server/
  dockerfile: /home/ubuntu/dockerProject/zabbix_server/Dockerfile
  volumes:
    - /home/ubuntu/dockerProject/shared/:/var/lib/zabbix_server
  tty: true

zabbix_agent:
  build: zabbix-agent/
  dockerfile: /home/ubuntu/dockerProject/zabbix-agent/Dockerfile
  links:
    - zabbix_server
  volumes:
    - /home/ubuntu/dockerProject/shared/:/var/lib/zabbix_agent
  ports: 
    - "10050:10050"
  tty: true

#urbancode:
#  build: urbancode/
#  dockerfile: /home/ubuntu/dockerProject/urbancode/Dockerfile
#  volumes:
#    - /home/ubuntu/dockerProject/shared/:/var/lib/urbancode
#  ports:
#    - "8087:8087"
#    - "8443:8443"
#  mem_limit: 600m
