link-datastore:
  image: mysql
  volumes:
    - /home/ubuntu/linkvolume:/var/lib/mysql

link-my_mysql:
  image: mysql
  volumes_from: 
    - link-datastore
  environment:
    - MYSQL_ROOT_PASSWORD="root"

link-wordpress:
  image: wordpress
  ports:
    - 8085:80
  links:
    - link-my_mysql:mysql

#link-php:
#  image: reinblau/php-apache2
#  ports:
#    - 8088:80

link-from_file:
  image: rogue
  ports:
    - 8089:80
